### ISSUE TITLE
Naming Cobalt Tab

### ISSUE THREAD

**Issue by grandiris72** [joelacus/Cobalt#1]
Would it be possible to give users the ability to name the cobalt tab? Thanks! Great work so far!

**Comment by joelacus** [comment]
Thanks! There is an option to change the page name in Settings > General > Page, which changes the text in the tab. Is this what you mean?

**Comment by grandiris72** [comment]
_facepalm_ How did I miss that? Yup thats it. Thank again!

**Comment by joelacus** [comment]
haha no worries. I could rename it to "Page / Tab" to help make it more discoverable. This applies per workspace btw. I should probably make a note of that under the setting.
