### ISSUE TITLE
[BUG] RSS not generating proper links

### ISSUE THREAD

**Issue by ghost-of-cerberus** [joelacus/Cobalt#10]
Hi @joelacus. Thanks for the performance improvements over the past few versions, greatly appreciated. 😄 

With version 0.6.1 on Edge and Firefox, I've noticed that links for RSS articles and host sites aren't working as expected. Either the link to the site itself or the feed items will show "moz-extension://fec086b1-e817-4509-8065-affd763846aa/..." in Firefox or "chrome-extension://amacbboiepkngglbhkdmeobmgjmigpag/..." in Edge/Chrome, and indicate a "File Not Found" error when clicking.

Using the four following feeds as examples:
- https://hackaday.com/blog/feed/
- https://selfh.st/rss/
- https://mariushosting.com/feed/
- https://noted.lol/rss/

The site title URL for "Blog - Hackaday" and "Marius Hosting" show as the previously mentioned incorrect URLs whilst the article links themselves show and link correctly.
![image](https://github.com/joelacus/Cobalt/assets/72414011/03a1a80c-0647-483f-9400-e2d1558f93b4)

For "Noted" and "selfh.st", the title URLs are correct but the article URLs are incorrect whilst the site title URLs are correct.
![image](https://github.com/joelacus/Cobalt/assets/72414011/15ff23dd-451d-4e53-9966-54ba9b25da5b)

Not certain if relevant or not but I did notice that both Noted and selfh.st are hosted by Ghost, whilst Hackaday and Marius Hosting appear to be using WordPress.

As always, let me know if you need further information to investigate. Cheers.

**Comment by joelacus** [comment]
> Thanks for the performance improvements over the past few versions, greatly appreciated. 😄

You're welcome. I'm glad I could speed it up quite a bit :rocket:

Sorry about the RSS issue, thanks for letting me know. I've improved the RSS parser now so this will be fixed in the next update I have coming out soon :)
