### ISSUE TITLE
[Feature Request] Allow Bookmark Button Widget To Load Non-HTTP(s) Links

### ISSUE THREAD

**Issue by onekmilesbehind** [joelacus/Cobalt#11]
Hi there!

I currently use the [Open external links in a container](https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/) extension to setup "launcher" URLs to start blank browsing sessions in specific containers. I stumbled upon this extension and the Bookmark Button widget is the perfect visual pairing with those URLs, but I can't get things to work.

Using the Bookmark Group widget, I'm able to set the url (following the container extension's schema) to something like 
`ext+container:name=Personal&url=about:blank`
 and that successfully loads a blank tab in my 'Personal' container.

Using the Bookmark Button widget though, it auto-formats the urls to https:// so I end up with 
`https://ext+container:name=Personal&url=about:blank`

Is there any way to allow the Bookmark Button widget to behave similarly to the Bookmark Group widget in this regard? Or is this something Firefox/Mozilla restricts?

Thanks for taking a look!

**Comment by joelacus** [comment]
Hi. Sorry about that, I never thought of this edge case tbh. Normal websites without 'http://' or 'https://' would fail to load from an extension page, so I added a check to add it if it's missing. It should have added it for both the Bookmark Button and the Bookmark Group. Anyway, I can add a simple option to disable the 'https://' prefix.

Thanks for letting me know!

**Comment by onekmilesbehind** [comment]
A toggle would work great! I'm sure the way I'm using the widgets here is atypical compared to 99.9%+ of the user base. Thank you for entertaining this request!

**Comment by joelacus** [comment]
You're welcome :)

That's good you're using it differently, I need people to try to use it in ways I haven't thought of and report feedback so I can make it better. If you find any other issues or have general feedback for any improvements or features, please let me know!

I've just published the new version. The option is next to where you edit the link for the bookmarks.

**Comment by onekmilesbehind** [comment]
It works perfectly! Thank you for adding this functionality, really helps with my usage! I'll be diving into the config over the next few days at work to lay things out so I'll keep an eye out for any features or uses that aren't already built-in. Really tremendous work!
