### ISSUE TITLE
[BUG] Backup File Upload Button Alignment Issue in Settings

### ISSUE THREAD

**Issue by ghost-of-cerberus** [joelacus/Cobalt#2]
Thanks for the work on Cobalt Tab. Absolutely the dashboard I needed!

Noticed a bug in the 'Settings > Data > Restore > Upload Backup File' area where the 'Browse' button appears to over the button to upload a backup file:

![cobalt_tab_bug01 png](https://github.com/joelacus/Cobalt/assets/72414011/d19828a1-458e-48a1-9d12-e4a04119cd6c)

Bit of info:
- OS:  Windows 11 Professional 22H2 (Build 22621.2070) (64-bit)
- Browser:  Microsoft Edge - Version 115.0.1901.188 (Official build) (64-bit)
- Cobalt Tab Version:  0.4.1 (beta)

**Comment by joelacus** [comment]
Ah yeah, thanks for pointing this out. The only way really to customise the file picker button is to use a <label> (the Browse button) which triggers the file picker. It covers the original button perfectly in Firefox, but every browser is slightly different haha. I'll improve this, might also add a drag and drop area too.

I appreciate the detail in your comment :)

**Comment by ghost-of-cerberus** [comment]
> It covers the original button perfectly in Firefox, but every browser is slightly different haha.

Brilliant. Loaded it up in Firefox and, though on 0.40 beta, it appears to be more consistent than on Microsoft Edge (haven't tested Chrome) and I've noticed a few additional bugs in 0.41 beta (Edge) that I don't see in 0.40 beta (Firefox). I'll aggregate the discrepancies as I go along and put them all in one bug report in the next few days for you.

**Comment by joelacus** [comment]
haha, I'm in danger. For real though, thanks, I really appreciate the support and testing :)
The only difference between 0.4.0 and 0.4.1 is just a bug fix for Chrome based browsers. I primarily use and develop for Firefox, so it is likely I've missed a few little bugs in Chrome based browsers.

**Comment by joelacus** [comment]
Hi. I fixed this bug, but I was wondering if you found any others I can fix for the next update?

**Comment by ghost-of-cerberus** [comment]
Hi, @joelacus. I have and am actually aggregating them all now (apologies, I meant to post it before I went on leave but didn't get a chance to do so).

How would you like me to feedback? All noted items in one post? One post for each item? Just let me know and I'll provide my feedback shortly.

Thanks again for building Cobalt! 👍

**Comment by joelacus** [comment]
No worries. Listing them all in one post will be good thanks :)
