### ISSUE TITLE
[BUG] Issues noted in Firefox version 0.4.0 and Edge version 0.4.1

### ISSUE THREAD

**Issue by ghost-of-cerberus** [joelacus/Cobalt#4]
Hi @joelacus. Here is a quick list of the issues/bugs noticed between the current Edge and Firefox beta builds. I've broken the list down into the area/widget they were found and the related browser in brackets. I've also included images showing the issue where possible. Let me know if any of these don't make sense and I'll try to provide further detail. Cheers.

### All Widgets:
- Widgets with content that can scroll shows a white rectangle (scroll stop?) in lower right corner of widget window [Edge]
- Horizontal scrollbar is thicker than vertical scrollbar [Edge]
![image](https://github.com/joelacus/Cobalt/assets/72414011/0bb1b92a-3f51-4cc6-a8d4-3ca27c880c3b)

### Bookmark Button:
- copy, edit and delete functions overlays button (of average length); cannot see text on button and difficult to move without resizing or selecting one of the three functions [Edge, Firefox]
![image](https://github.com/joelacus/Cobalt/assets/72414011/d78dc1ad-d9da-419c-8f83-4f81c593c11d)

### Bookmark List:
- Widget 'Display' icons tiled end-to-end [Edge]
![image](https://github.com/joelacus/Cobalt/assets/72414011/94f4f14b-6f4e-4b0d-bdd8-d97f4d36fc7c)
- Button colour settings for bookmark list doesn't maintain after save and page refresh [Edge,Firefox]
- Cannot use a group with no name. Removing the name and saving the widget replaces the blank name with 'bookmarks'. [Edge]

### Group Widgets:
- Bookmark button one row high extends beyond border of "Group Widgets" widget if also one row high [Edge, Firefox]
![image](https://github.com/joelacus/Cobalt/assets/72414011/6d803b5c-db12-48d5-91c0-a73f6aaf5195)

### Weather:
- Add location renders oversized box for location (information falls off-screen) [Firefox]
![image](https://github.com/joelacus/Cobalt/assets/72414011/059c4904-7241-489f-ae8e-a0d6ce73879e)

### Photo:
- Image Move sliders do not show correct values when moved quickly [Edge, Firefox]
![image](https://github.com/joelacus/Cobalt/assets/72414011/54bc2ab1-c227-4503-be28-439835df5bf9)
- Image Move slider values do not appear to correctly reflect value; doesn't seem intuitive [Edge, Firefox]
  - (i.e., if horizontally moved 100%, should the image not be moved the full image width to the left or right from its starting x position thus rendering it out of the display area?)

### RSS News:
- Various RSS and Atom feeds do not load; RSS specifics unknown [Edge, Firefox]
  - (i.e., https://www.reddit.com/r/all.rss = no, http://www.roysac.com/blog/atom.xml = no, https://techcrunch.com/feed/ = yes)

---
### System/Testing Info:
- OS: Windows 11 Professional 22H2 (OS Build 22621.2134) (64-bit)
- Browser: Microsoft Edge - Version 115.0.1901.203 (Official build) (64-bit) - Cobalt Tab Version: 0.4.1 (beta)
- Browser: Mozilla Firefox - Version 116.0.2 (64-bit) - Cobalt Tab Version: 0.4.0 (beta)

**Comment by joelacus** [comment]
Very thorough. Thank you for taking the time to provide detailed feedback. I'll make a start on the fixes.

**Comment by joelacus** [comment]
Hi. Just an update. I've fixed bugs 1, 2, 4, 5, 7, and 11 so far.

The weather location bug I can't seem to replicate, but I'm thinking about moving that section into the widget editor anyway, because I want the weather widget to be able to become small, and having the add weather section where it is now won't work.

"Cannot use a group with no name." This seems to work for me on both browsers, do you still have this issue?

Regarding the RSS bug, this feed http://www.roysac.com/blog/atom.xml doesn't seem to exist anymore. However, the Reddit one not working was because Reddit blocked my fetcher because it didn't give it a user agent, that's fixed now.

I'll try to release an update this week sometime.

If you have found any other bugs since, let me know :)

**Comment by ghost-of-cerberus** [comment]
Hi @joelacus.

> The weather location bug I can't seem to replicate, but I'm thinking about moving that section into the widget editor anyway, because I want the weather widget to be able to become small, and having the add weather section where it is now won't work.

For the weather bug, it I was able to repeat it during my testing but don't recall having any issues recently. It seems/seemed like a DPI scaling-related bug but I don't recall making any DPI adjustments during testing. I'll check again and provide detailed steps to replicate as needed.

>"Cannot use a group with no name." This seems to work for me on both browsers, do you still have this issue?

So, I just tested again and was able to replicate, but only when attempting to use the default "bookmarks" group (created when first adding the Bookmark Group widget) or if there are no other groups with a title. 
In my test I added a new Bookmark Group widget and cleared the name of the default "bookmarks" group to make it empty. If I add a bookmark to that group and save the layout, things "appear" to work as expected. When I refresh the page or edit the Bookmarks Group widget again, the menu shows that my previously blank group name has been reverted to the "bookmarks" group title. The issue does not seem to occur if as long as I do not attempt to reuse the default "bookmarks" group as a blank group OR if there exists another group with a name in the widget.
Let me know if you need further information and I will see if I can make a recording to display the issue.

>I'll try to release an update this week sometime.
>If you have found any other bugs since, let me know :)

Sounds good. Haven't come across anything else recently, but definitely will let you know if I do. :)

**Comment by joelacus** [comment]
That bookmark group bug is strange, I still can't replicate the issue :s. A recording would be helpful thanks :)

**Comment by ghost-of-cerberus** [comment]
Hi @joelacus. Regarding the Bookmark List "bug", it might not actually be a bug with Cobalt but user error.

Though I was able to replicate it again on Wednesday, I attempted to replicate again today to record and used the steps I had been previously (which are documented above) and have not been able to replicate it at all. If you're not able to reproduce it and I'm having difficulties, unless someone else chimes in and can confirm they can reproduce the issue, I would say this was user error and strike it from the list.

I'll continue to try reproduce and - if I am able to do so - will record and provide a complete step-by-step to replicate.

Apologies.

**Comment by joelacus** [comment]
No worries haha, it was good to mention it anyway just in case there was a problem, maybe there is and it's hit or miss.

**Comment by joelacus** [comment]
Hi. I've just published 0.5.0 with the bugs fixes, except for bug 3, 9 and 10. I started looking into optimising the performance as well, but I thought I should get the fixes I have done out first. The update for Firefox is out now, Chrome and Edge will take a bit longer to be approved. Let me know if you still have any issues.

**Comment by ghost-of-cerberus** [comment]
Hi @joelacus. Thanks for the new version and the fixes! Just got the updated Edge extension a few days ago and have been testing the fixes.

Most things seem okay thus far but I've noted a fairly significant on the Edge extension. When upgrading, the positioning of all widgets was lost and became condensed to the far left of the window. Initially, I thought it may have been due to a change between 0.41 and 0.50 (they're betas, right? 🤣) so reset everything to default and manually recreated my dashboard. However, this has recurred a few times since then. 

From testing so far, it seems that this can be replicated if the Edge in opened windows (i.e., not full-screen) and the dashboard loads before the window can be maximised.

I've attached a copy of my Cobalt backups before and after the issue (labelled pre- and post-, respectively) and a screenshot of the issue below:
![image](https://github.com/joelacus/Cobalt/assets/72414011/25f20f07-ea25-4ef7-8003-24283294943a)
I haven't been able to replicate this issue on Firefox, so it may be exclusive to Edge (or Chromium-based browsers).

- [post-0.50__CobaltStart_backup_data_2023_Sep_17_181515.json.txt](https://github.com/joelacus/Cobalt/files/12643562/post-0.50__CobaltStart_backup_data_2023_Sep_17_181515.json.txt)
- [pre-0.50__CobaltStart_backup_data_2023_Sep_15_222334.json.txt](https://github.com/joelacus/Cobalt/files/12643563/pre-0.50__CobaltStart_backup_data_2023_Sep_15_222334.json.txt)

**Comment by joelacus** [comment]
I'm sorry, this is quite a significant bug. I've not encountered this before, but I'm glad you've brought it to my attention.

I was really confused how this could happen at first, but I have figured out why. The widgets are based on Gridstack, and when the browser window is at a certain width, the widgets align to the left and should become full width of the window. This usually is a feature so you can see widgets on narrow screens, however, for some reason the widgets here don't go full width, but the main issue is that when the save function runs, it can no longer see the width values of the widgets and sees that they are all at position '0' along 'X'.  So this has been a bug since version 0.1 haha, my bad.

Here's a demo. The code at the bottom in this video represent the two widgets and their position and size values.
https://github.com/joelacus/Cobalt/assets/43767965/74047967-622c-4bed-b389-c3af7df8e8ae

I will need to think how I can solve this so it isn't an issue in the future.

On a positive note though, I have significantly sped up the load times in the next version. Loads in about 200ms now :D

**Comment by ghost-of-cerberus** [comment]
>Edit: I fixed it. This shouldn't happen in future versions. My mistake was getting the values from the widget attributes directly, rather than serialising the grid with the gridstack api, and then getting the values for each widget.

Definitely a much better solution. 😄

>Btw, I have significantly sped up the load times in the next version. Loads in about 200ms now :D

Brilliant! Looking forward to that release. The speed increase in 0.50 is noticeable but anything to bring it down further would be welcome. 😄
