### ISSUE TITLE
[Translation Help] Portuguese translation

### ISSUE THREAD

**Issue by imSarahOwl** [joelacus/Cobalt#5]
Hello, I am a Portuguese speaker that started using Cobalt and I am enjoying my time with it. I saw in the language section that translations are welcome, and I would like to help translate Cobalt to Portuguese, but I am a bit confused about how I can do that. Could you give me some directions? Cheers!

**Comment by joelacus** [comment]
Hi, I'm glad you're enjoying it! Sorry for the confusion, I forgot to add the locales and instructions.
I have now uploaded the locales folder with instructions, and have prepared the files for Portuguese ready for translation.
Thank you for helping :)

**Comment by imSarahOwl** [comment]
Once again, thank you so much for the incredible extension. I'll start translating right now :)

**Comment by joelacus** [comment]
Hi. I'm getting ready to release a new update soon, and wondered if you had done the translations? I would love to include them :)

**Comment by imSarahOwl** [comment]
Hello, sorry for taking a long time. I am just finishing up some little things right now. I believe that I'll be done in around 30-60 minutes. Thank you for the patience :)
