### ISSUE TITLE
Selecting Portuguese translation breaks Cobalt completely

### ISSUE THREAD

**Issue by imSarahOwl** [joelacus/Cobalt#7]
Hi, I'm Sarah, the person that did the Portuguese translation for Cobalt.
I have found an issue on the latest Cobalt version. I'm on the latest version for Cobalt(0.6.0) and Firefox(118.0.2).

### Steps to Reproduce

1.  Install Cobalt Tab on Firefox
![Screenshot_01](https://github.com/joelacus/Cobalt/assets/44755028/8793abbe-6340-4237-9544-c27424fcce38)

2. Set the Portuguese language on the settings and click to apply
![Screenshot_02](https://github.com/joelacus/Cobalt/assets/44755028/e464a1b9-896b-427e-91e2-0233022fb567)

3. Reload the page, and you will get this
![Screenshot_03](https://github.com/joelacus/Cobalt/assets/44755028/7dd3d1da-a656-40a0-bc37-9d76b2d8be87)

### Additional Info

- The issue is not reproducible on Chrome, because the extension has not been updated there yet
- By looking on the console, I was able to discover that all the errors come from the file `index-c6e3a02ac4be2d9715d1.js`, and the specific error is `Uncaught (in promise) TypeError: c is undefined`
![Screenshot_04_error](https://github.com/joelacus/Cobalt/assets/44755028/612d7c07-5f30-42fe-980e-80c97a8d0567)
- For the users, a temporary fix is going to Storage on the F12 menu, going to Local Storage, finding `saveLanguage` and changing it from `pt` to `en`(English) or `fr`(French)
![Screenshot_05_solution](https://github.com/joelacus/Cobalt/assets/44755028/ab9843b5-096f-4cec-a3d3-2713cab9f1d4)
(My firefox is in Spanish, so the option names will be different)

**Comment by joelacus** [comment]
Hi, I'm really sorry about this. I've already fixed the problem and an update will be out tonight.
Basically, I forgot to link one of the translation files to the clock widget and it got confused :(
Well done for figuring out a temporary fix.

**Comment by imSarahOwl** [comment]
Hi, thanks for the quick response
Don't worry, it happens to all of us. Once again, thank you for the amazing work you have done on this extension

**Comment by joelacus** [comment]
I've just published the update, it should work now haha. The 0.6.0 update was a pretty big one with a lot of changes, so if you find any other bugs, please let me know, thanks :)
