### ISSUE TITLE
Hi, I want to help you with some translations.

### ISSUE THREAD

**Issue by Informationsbrist** [joelacus/Cobalt#8]
Hi, I found this very nice browser addon and I want to use it, but there is no translation on Swedish. That's why I am already working on to translate from English to Swedish. Once I am done with all the translations I will share all the three files to you so that you can add them to locales. If you have any questions, just contact me here on Github. Thanks! :)

**Comment by joelacus** [comment]
That's amazing, thank you! I'll include them in the next update :)

**Comment by Skuggfigur** [comment]
Here I come with an update for you. :) This is the last text I have to translate and then I am 100% done with almost everything. 

This is how much I still have left to translate from English to Swedish (everything above this piece of text has already been translated by me):

"SettingsWorkspace1": "Go To Workspace Button Style",
	"SettingsWorkspace2": "Disabling this does not delete any saved workspaces",
	"SettingsWidgetAlignGuide1": "This is only visible when in Edit Mode",
	"SettingsWidgetMargins1": "Requires Page Reload. Side effect, makes widgets slightly smaller when increased.",

	"steam1": "Auto Load Workspace",
	"steam2": "Find out your Steam ID 64",
	"steam3": "Find Steam App IDs for games",
	"steam4": "Intended for Steam's in-game overlay browser.",
	"steam5": "Automatically load a certain workspace when running a specific game.",
	"steam6": "You must set your Steam profile game details to public for this to work.",
	"steam7": "Use the edit buttons in the workspaces menu to add Steam App IDs.",
	"steam8": "Make sure your Steam profile and game details are public.",
	"steam9": "You must have a game running for the test.",
	"steam10": "Make sure your Steam ID 64 is correct.",
	"steam11": "It should be a long number, not your username.",
	"steam12": "If your Steam ID 64 is correct, a server monkey will be despatched to investigate the error.",
	"steam13": "Sorry for any inconvenience.",

	"ToolTipWorkspace": "Automatically loads a workspace when running a specific game. You need to enable this option in the settings menu.",
	"ToolTipDownloadWorkspace": "Download a save file for this workspace. You can share this with other people. If you enable widgets, this will include any widget content.",
	"ToolTipFontBad": "Not Found",
	"ToolTipFontGood": "Looks Good",

	"welcome1": "Welcome To Cobalt Tab!",
	"welcome2": "Click Next to get started",
	"welcome3": "Cobalt lets you fully customise the layout and style of your homepage.",
	"welcome4": "Here are a couple quick style options to get started:",
	"welcome5": "Enter Edit Mode to access more colours and style options in the settings menu",
	"welcome6": "Add more functionality with widgets",
	"welcome7": "Add new widgets from the settings menu",
	"welcome8": "Move and Resize Widgets",
	"welcome9": "In Edit Mode you can move and resize widgets",
	"welcome10": "Edit the widget styles and properties here",
	"welcome11": "Add multiple workspaces with their own layouts, widgets and style options",
	"welcome12": "You're All Set! :)",
	"welcome13": "This extension/site is still a work in progress. Any bugs/issues can be reported, along with any ideas and feature suggestions, here",
	"welcome14": "Join the Reddit community to get inspiration and post your designs!"

**Comment by joelacus** [comment]
Ah ok, yeah it won't accept all files here because typically you would send a "pull request" to upload changed files, but I appreciate you are new and this can be complicated. Uploading them here is fine, thank you :)

**Comment by joelacus** [comment]
Hey, I was wondering if you have done anymore of the translations? I'm getting ready to release a new update soon. No worries if they aren't 100% complete yet, I can add them as they are for now. I have added new words in this next update, so the translation files will have to be updated anyway. Thanks :)
